### ISSUE TITLE
Post dating docs

### ISSUE THREAD

**Issue by mrmsbarnes** [mdickinson/bigfloat#113]
Post dating checks is unseemly at best.  You definitely should not be post dating docs such as
https://readthedocs.org/projects/bigfloat/downloads/pdf/latest/
Who knows what will happen by Dec. 31, 2020?  You don't.  It destroys trust when you do things like this.

**Comment by mdickinson** [comment]
> It destroys trust when you do things like this.

Please could you keep the discussion civil, and remember that this is an entirely volunteer project?

I've no idea how that date got there. It's definitely not something I intentionally put there, and no such date is specified anywhere in the configuration. I suspect it's a side effect of some part of Sphinx or readTheDocs configuration. If you have any ideas what part of the configuration I need to change, I'd welcome help with fixing this.

**Comment by mdickinson** [comment]
A local Sphinx build produces the correct date, as expected, which makes it more likely that this is coming from RtD somehow.
<img width="702" alt="Screenshot 2020-08-09 at 15 08 12" src="https://user-images.githubusercontent.com/662003/89734163-51a28400-da52-11ea-9da3-6f6f6a5c766b.png">

**Comment by mdickinson** [comment]
This bug report looks related: https://github.com/readthedocs/readthedocs.org/issues/6496
