### ISSUE TITLE
Make available on Python 3.5 and Python 3.6

### ISSUE THREAD

**Issue by mdickinson** [mdickinson/bigfloat#74]
This should just be a matter of updating the Trove classifiers in the setup script, and adding Python 3.5 and Python 3.6 to the CI setup.

At the same time, we might consider dropping support for Python 2.6 and earlier Python 3 versions.

**Comment by FrankenApps** [comment]
It would also be good if it could be pointed out somewhere in the docs, that 3.5 and 3.6 are not supported at the moment, it might people trying to install on such a version save some time...

**Comment by mdickinson** [comment]
Well, really they _are_ supported. :-) I'm a little bit surprised that the general "Python :: 3" classifier isn't enough here. Do you know what logic is being used to interpret the classifiers? If I simply drop the 3.x subversion classifiers, does that logic assume that _all_ Python 3.x versions are supported?

**Comment by mdickinson** [comment]
I've updated the trove classifiers directly on PyPI, so bigfloat should now be available for Python 3.5 and Python 3.6 without any need for a new release. I'll leave this issue open as a reminder to myself to update the classifiers here, too.

**Comment by mdickinson** [comment]
@FrankenApps: What mechanism are you using to install bigfloat, and does it work for you now? `pip install bigfloat` is working for me on OS X / Python 3.6, but then again, it was already working for me before I changed the classifiers on PyPI.

**Comment by hugovk** [comment]
Here's the pip installs for bigfloat from PyPI for the last year:
```
$ pypinfo -d 365 --percent --pip bigfloat pyversion
python_version percent download_count
-------------- ------- --------------
2.7              63.2%          3,047
3.5              17.9%            865
3.6              13.9%            668
3.4               4.8%            230
3.3               0.1%              5
2.6               0.1%              4

```
